### ISSUE TITLE
Generalising the code for initialising ClimaOcean with different datasets

### ISSUE THREAD

**Issue by taimoorsohail** [CliMA/ClimaOcean.jl#468]
I noticed that the `LinearlyTaperedPolarMask` and associated functions are dataset agnostic, i.e., the don't care what dataset is input. So, shouldn't this and associated functions be in the `DataWrangling.jl` file instead? This would ensure future support for EN4/WOA for example can access the same function instead of having to define a new one for each dataset.

**Comment by simone-silvestri** [comment]
Good idea! I think they are there for historical reasons before we generalized the concept of `Metadata` (before there was only `ECCOMetatdata`. The mask definitely fits better in the `DataWrangling` module.

**Comment by taimoorsohail** [comment]
I'm going to use this issue to discuss a future PR on generalising the initialisation code so we can have multiple different datasets initialised in ClimaOcean... the `LinearlyTaperedPolarMask` function is a good example of such needed generalisation.

**Comment by navidcy** [comment]
resolved by #469

**Comment by taimoorsohail** [comment]
@navidcy this issue wasn't resolved - as you can see the issue is for the general process of refactoring the code so it general and can take in multiple datasets. I am happy to have that conversation on the PR #467 instead though.

**Comment by navidcy** [comment]
You are correct; my bad!

**Comment by navidcy** [comment]
(I think I read the first comment of the issue and I thought that moving `LinearlyTaperedPolarMask` up one level was all that was required here.)
